version: '3'

services:

  web:
    build: .
    command: sh entrypoint.sh
    ports:
    - 8000:8000
    depends_on:
    - db
    - redis

  db:
    image: postgres
    volumes:
    - data:/var/lib/postgresql/data/
    ports:
    - 5432:5432

  redis:
    image: redis
    ports:
    - 6379:6379

volumes:
  data: {}